name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api-newman:
    runs-on: ubuntu-latest
    steps:
  		- uses: actions/checkout@main

	  	- name: Docker for newman
		  	run: |
			  docker run -v $(pwd)/test:/etc/newman -t postman/newman:latest run "HttpbinForNewman.json" --reporters="cli"`